### ISSUE TITLE
File constructor parameters order are wrong on android?

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-plugin-file#252] opened 2018-09-10 07:35 UTC
I have the following code:
```
let blobToSave = this.nonAngularObjectsFactory.b64ToBlob(responseData, "application/octet-stream");
let file = new File([blobToSave], route.name + ".gpx");
console.log(file);
```
Which basically gets a base64 string from the server, converts it to blob and creates a file from it.
Here is the output of the console in the browsers:
![image](https://user-images.githubusercontent.com/3269297/45282830-be1e4c80-b4e4-11e8-8dd3-2f4bb74078a1.png)
And here is the output of the console when running on an android simulator:
![image](https://user-images.githubusercontent.com/3269297/45282871-e312bf80-b4e4-11e8-9257-75dcd1a1bf1d.png)
Am I doing something wrong?
Looks like the name is the first parameter (the blob)...?

**Comment by rpanadero** [comment] 2018-11-05 11:30
Same issue here. Is there a workaround to avoid this ?

Thanks in advance

**Comment by HarelM** [comment] 2018-11-05 11:33
I have migrated to use blobs in most part of my code and just use File when I know I'm running a code on a device and not in the browser. But it's a hack...

**Comment by rpanadero** [comment] 2018-11-05 12:29
Ok, I will try to do the same, thank you @HarelM . In my case I think that it is a little bit more complicated as I'm using other third party libraries which could be affected for this issue. For example, this library, https://github.com/digitalascetic/ngx-pica, internally generates compressed files which are built wrongly due to this issue (I guess) and I think that it is complicate to deal with this unexpected behavior.

**Comment by HarelM** [comment] 2018-11-05 18:46
@rpanadero I agree this is a problem and it should be fixed, IMHO, this is why I reported it.
I tried to use ngx-pica but it had horrible performance so I ended up writing some code to compress images on my own (taken from SO), so I didn't need it, most libraries I use do not use files so I was in luck...
Relevant code can be found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/services/image-resize.service.ts it uses `File` but this is because `File` derives from `Blob`.

**Comment by breautek** [comment] 2023-01-25 00:46
`File` is not what you think it is. Due to some old decisions... it's actually a [cordova object](https://github.com/apache/cordova-plugin-file/blob/master/www/File.js), not browser `File` API.

This issue is tracked at https://github.com/apache/cordova-plugin-file/issues/316 so I'll be closing this issue.

**Closed by breautek** 2023-01-25 00:46 UTC
Labels: platform: android, support
