### ISSUE TITLE
FILE NOT FOUND When external file requested

### ISSUE THREAD

**Issue by yoprogramo** [apache/cordova-plugin-file#303] opened 2019-03-25 12:36 UTC
I try to open a file on Downloads folder using cordova-plugin-file.

This is the file:

file:///storage/emulated/0/Download/backup_2.nmp

When I call resolveLocalFileSystemURL with this path I receive this object:

```
{File {name: "backup_2.nmp", localURL: "cdvfile://localhost/sdcard/Download/backup_2.nmp", type: null, lastModified: 1553501140000, lastModifiedDate: 1553501140000, …}
end: 336
lastModified: 1553501140000
lastModifiedDate: 1553501140000
localURL: "cdvfile://localhost/sdcard/Download/backup_2.nmp"
name: "backup_2.nmp"
size: 336
start: 0
type: null
...
}
```

That means that the app has access to this file (size and dates are ok), but onloadend the result is null

```
_error: FileError {code: 1}
_localURL: "cdvfile://localhost/sdcard/Download/backup_2.nmp"
_progress: 0
_readyState: 2
_realReader: FileReader {readyState: 0, result: null, error: null, onloadstart: null, onprogress: null, …}
```

Meanwhile if I select a file inside the app root everythig goes well:

file:///storage/emulated/0/Android/data/com.biblioeteca.apps.myapp/files/export.nmp

```
_error: null
_localURL: "cdvfile://localhost/files-external/export.nmp"
_progress: 336
_readyState: 2
_realReader: FileReader {readyState: 0, result: null, error: null, onloadstart: null, onprogress: null, …}
_result: "..."
```

What I am doing wrong?

**Comment by madeleineberger** [comment] 2019-04-17 09:46
I've got the same issue for browser and Android 8 and newer.
Interesstingly on Android 5.0 it works fine.

**Comment by janpio** [comment] 2019-06-07 13:51
Can you share some simple code so this becomes reproducible?

**Comment by mese79** [comment] 2019-07-06 16:10
I have the same issue with latest cordova file plugin and android 8.  
```
var fileName = window.cordova.file.applicationStorageDirectory + 'databases/some.db'
var directoryName = window.cordova.file.externalRootDirectory

window.resolveLocalFileSystemURL(fileName, (file) => {
    console.log('[!] Database exists: ' + fileName);
    console.log('[!] Storage: ' + directoryName);
					
    window.resolveLocalFileSystemURL(directoryName, (directory) => {
        console.log('[!] Directory: ' + directory.toURL());
						
        directory.getDirectory("backup", {create: false, exclusive: false}, (directoryBackup) => {
	    console.log('[!] Directory: ' + directoryBackup.toURL());
	    file.copyTo(directoryBackup, name, (copiedFile) => {
                 console.log('[!] Copy success');
	    }, (error) => {
		 console.log('[!] Copy failed: ' + error.code);
	    })
						
	}, (error) => {
            console.log('[!] Backup Directory not found: ' + directoryName + 'Backup' + ' errorcode: ' +  + error.code);
	})
					
    }, (error) => {
	console.log('[!] Directory not found: ' + directoryName + ' errorcode: ' +  + error.code);
    })
}, (error) => {
    console.log('[!] Database not found: ' + fileName + ' errorcode: ' +  + error.code);
})
```

**Comment by mese79** [comment] 2019-07-14 15:41
Any update on this?

**Comment by breautek** [comment] 2022-12-19 04:16
With Android's scoped storage model enforced in API 30, your application my write to external directory but may not overwrite files that other apps have created/written to.

Additionally, custom directories inside the external storage is now forbidden, only the predefined directories (e.g. `Download`, `Documents`, etc) can be written to. The `externalRootDirectory` is also not a writable path anymore.

An example of a working test app can be found:

```javascript
document.addEventListener('deviceready', onDeviceReady, false);

var testFiles = async function() {
    window.resolveLocalFileSystemURL(cordova.file.externalRootDirectory + 'Download', (downloadsDirEntry) => {
        console.log('DOWNLOADS', downloadsDirEntry);
        downloadsDirEntry.getFile('test1.txt', { create: true }, (fileEntry) => {
            fileEntry.createWriter((writer) => {
                writer.onwriteend = () => {
                    console.log('file written');
                };

                writer.onerror = (error) => {
                    console.error('WRITE ERROR', error);
                };

                writer.write(new Blob(['Hello! from app 1'], { type: 'text/plain'}));
            });
        }, (error) => {
            console.error('FILE OPEN', error);
        })
    }, (error) => {
        console.error('DIR READ', error);
    });
};

function onDeviceReady() {
    // Cordova is now initialized. Have fun!

    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
    document.getElementById('deviceready').classList.add('ready');

    testFiles();
}
```

Closing this issue as not a bug. However if you think you have foound a bug, please create a new issue with the issue form filled out. Alternatively support questions can be asked on our [Discussions board](https://github.com/apache/cordova/discussions).

**Closed by breautek** 2022-12-19 04:16 UTC
Labels: platform: android
