### ISSUE TITLE
Not seeing files that are stored on the Android device

### ISSUE THREAD

**Issue by artisanphil** [apache/cordova-plugin-file#239] opened 2018-08-16 08:41 UTC
The issue has been described in this question: 
https://stackoverflow.com/questions/42490558/not-seeing-files-that-are-store-on-the-android-device-using-cordova-file-plugin

I'm facing the same issue and was only able to solve it by downgrading to Android API 22 as the author in the Stackoverflow question did. 

When looping through all directories on the phone, it will only see files in the directory where the app is stored, but not files stored for example in the download folder of the SD Card.

This is my function:
```
 var localURLs    = [
      this.file.cacheDirectory,
      this.file.applicationDirectory,
      this.file.applicationStorageDirectory,
      this.file.dataDirectory,
      this.file.documentsDirectory,
      this.file.externalApplicationStorageDirectory,
      this.file.externalCacheDirectory,
      this.file.externalRootDirectory,
      this.file.externalDataDirectory,
      this.file.sharedDirectory,
      this.file.syncedDataDirectory
    ];
 loopThroughDirectories(localURLs, function(){
    });

function loopThroughDirectories(localURLs, callback) {
      for (i = 0; i < localURLs.length; i++) {

        console.log("directory: " + localURLs[i]);
        if(i == (localURLs.length - 1))
        {
          loading.dismiss();
          callback();
        }
        if (localURLs[i] === null || localURLs[i].length === 0) {
          continue; // skip blank / non-existent paths for this platform
        }
        window.resolveLocalFileSystemURL(localURLs[i], addFileEntry, addError);
      }
    }

var that = this;
    var addFileEntry = function (entry) {
      console.log("addFileEntry");
      var dirReader = entry.createReader();
      dirReader.readEntries(
        function (entries) {
          console.log("nr of entries: " + entries.length);
          var i;
          for (i = 0; i < entries.length; i++) {
            console.log(entries[i].fullPath);
            if (entries[i].isDirectory === true) {
              // Recursive -- call back into this subdirectory
              addFileEntry(entries[i]);
            } else {
              if(entries[i].fullPath.endsWith(".apkg") && entries[i].fullPath.search("/AnkiDroid/") == -1)
              {
                console.log(i + ": " + entries[i].fullPath);
                that.arrFiles.push({nr: i, fullPath: entries[i].fullPath, nativeURL: entries[i].nativeURL}); 
              }
            }
          }
        },
        function (error) {
          console.error("readEntries error: " + error.code);
        }
      );
    };

 var addError = function (error) {
      console.error("getDirectory error: " + error.code);
    };
```

It's used in this project for finding all files on a phone with the apkg extension:
https://github.com/phil4literacy/TeachMeWords

**Comment by janpio** [comment] 2018-08-16 08:46
So API level <= 22 could see all files, API level >22 can only see application files?

**Comment by phil4literacy** [comment] 2018-08-16 09:12
Yes, mostly. For example with API 28 it found files here: 
file:///storage/emulated/0/Android/data/com.sil.teachmewords/files/

and also under the plugin folders:

/www/plugins/cordova-plugin-zip/
/www/plugins/cordova-plugin-file/www/browser/

but none under any of the folders that are not related to the app, e.g. /Download

**Comment by phil4literacy** [comment] 2018-08-16 09:13
BTW, new apps created with API 22 are no longer allowed to be uploaded to Google Play, so I'm currently stuck...

**Comment by premtemp1** [comment] 2018-09-30 17:31
I am having the same issue.. Did you find a solution?

**Comment by phil4literacy** [comment] 2018-10-01 04:52
@premtemp1 : Sadly no. Still waiting and hoping somebody will work on fixing this. Looks like the plugin has been abandoned though, as if people no longer use files but do everything in the cloud... But apparently I'm not the only one who needs access to the filesystem.

**Comment by janpio** [comment] 2018-10-01 08:54
It has not been abandoned, there is just a pretty massive backlog of stuff in general regarding Cordova core plugins that has to be taken care of. I am currently working through all the testing issues for example: https://github.com/apache/cordova/issues/28

**Comment by sabrinetseng** [comment] 2018-11-06 10:58
8.1.2 (cordova-lib@8.1.1), API level 27
android 5.0 is OK.
android 8.1 dirReader.readEntries is not seeing files in directory.

**Comment by moridianmess** [comment] 2019-02-12 15:29
Hey all, has there been any movement on this? 6 months later I can confirm this is still an issue. I need to be able to access users files on both iOS and android, but I also need the ability to restrict by mime types and choose whether multi-select is enabled or not, depending on the scenario. There seems to be a lack of plugins that are able to do this, file-chooser and file-picker both seem to be limited to one file at a time. I have written a component in Ionic but obviously I need the android users folders to be accessible to be able to use it. Any information or work around to gain access to file.externalRootDirectory would be massively appreciated.

Thanks
Marc

**Comment by gsdiama** [comment] 2019-05-23 08:02
Hi everybody,

Any news? I have exactly the same problem. I'm programming an hybrid Ionic 3 app, that works perfectly except in Android 9.0(API Level 28) that asks for permissions (and I accept) but when I try to access local files, the device returns no folders. In Android 8 and less there is no problem. I use cordova-file.

I will much appreciate if anyone could answer me.

Thanks in advance.

Yours faithfully,

GSDiama
__________________________________________

>cordova info

Collecting Data...


Node version: v8.11.3

Cordova version: 8.0.0

Config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="20003" id="com.XXXXXX.YYYYYYYY" version="2.0.0"
xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0
">
    <name>XXXX</name>
    <description>XXXXX</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Fr
amework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="loadUrlTimeoutValue" value="700000" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png"
 />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png"
 />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png"
 />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.pn
g" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.
png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-ico
n.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-
ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-
mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-
hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land
-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-lan
d-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-la
nd-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-
ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-
mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-
hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port
-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-por
t-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-po
rt-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" /
>
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" /
>
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" /
>
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" /
>
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" /
>
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" /
>
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167"
 />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58"
/>
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87"
/>
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024"
/>
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.p
ng" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width=
"750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width=
"1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.p
ng" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipa
d.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadp
ro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.pn
g" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad
.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpr
o.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.pn
g" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" wi
dth="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width
="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~any
any.png" width="2732" />
    </platform>
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.1" />
    <plugin name="cordova-plugin-device" spec="^1.1.4" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.16" />
    <plugin name="cordova-sqlite-storage" spec="^2.0.4" />
    <allow-navigation href="http://192.168.0.227:8100" />
    <allow-navigation href="http://192.168.0.227:8101" />
    <allow-navigation href="http://192.168.0.227:8102" />
    <allow-navigation href="file://*/*" />
    <allow-navigation href="*" />
    <plugin name="cordova-plugin-actionsheet" spec="^2.3.3" />
    <plugin name="cordova-plugin-camera" spec="^4.0.3" />
    <plugin name="cordova-android-support-gradle-release" spec="^2.1.0">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-file-opener2" spec="^2.2.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <engine name="android" spec="^6.4.0" />
</widget>


Plugins:

cordova-android-support-gradle-release,cordova-plugin-actionsheet,cordova-plugin
-camera,cordova-plugin-device,cordova-plugin-fcm,cordova-plugin-file,cordova-plu
gin-file-opener2,cordova-plugin-file-transfer,cordova-plugin-ionic-webview,cordo
va-plugin-network-information,cordova-plugin-splashscreen,cordova-plugin-whiteli
st,cordova-sqlite-storage,ionic-plugin-keyboard

Android platform:

Available Android targets:
----------
id: 1 or "android-23"
     Name: Android 6.0
     Type: Platform
     API level: 23
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 2 or "android-24"
     Name: Android 7.0
     Type: Platform
     API level: 24
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : android-tv/x86, default/x86, default/x86_64
----------
id: 3 or "android-25"
     Name: Android 7.1.1
     Type: Platform
     API level: 25
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 4 or "android-26"
     Name: Android 8.0.0
     Type: Platform
     API level: 26
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 5 or "android-27"
     Name: Android 8.1.0
     Type: Platform
     API level: 27
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
----------
id: 6 or "android-28"
     Name: Android 9
     Type: Platform
     API level: 28
     Revision: 6
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, Android
WearRound390x390, AndroidWearRound400x400, AndroidWearRound454x454, AndroidWearR
ound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin320x300, AndroidWe
arRoundChin360x325, AndroidWearRoundChin360x326, AndroidWearRoundChin360x330, An
droidWearSquare, AndroidWearSquare240x240, AndroidWearSquare320x320
 Tag/ABIs : android-wear/x86, google_apis_playstore/x86, google_apis_playstore/x
86_64
----------
id: 7 or "android-Q"
     Name: Android 10 (Preview)
     Type: Platform
     API level: Q
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : google_apis_playstore/x86, google_apis_playstore/x86_64
 
__________________________________________
 
>ionic info

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\jc\AppData\Roaming\npm\node_mod
ules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.0.1

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : not available

System:

 (C:\Program Files (x86)\Android\android-sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 7

**Comment by fragatak** [comment] 2020-01-15 20:48
I think I have got this working in initial testing. 

I added 
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" /> 
to the AndroidManifest.xml. I also added the cordova-plugin-android-permissions aswell. So I am not completely sure which one might have made it work. 

I can now see the Downloads off of cordova.file.externalRootDirectory and when doing 'file:///sdcard' (device root internal directory for shared files) I can now see everything. 

I am using API level 26 currently. I added a view from Chrome remote console. 

![Annotation 2020-01-15 154430](https://user-images.githubusercontent.com/3291636/72469709-fbb47900-37ad-11ea-8734-8b3d73845664.png)

**Comment by fragatak** [comment] 2020-01-16 22:03
It looks like the cordova-pluging-android-permissions is doing something the Manifest.xml is not checking for. I removed the permissions from the Manifest and did the checking via the pluging, everything works now.

**Comment by Zi1989** [comment] 2020-01-19 17:08
@fragatak how did you do the checking via the plugin. I am currently trying to store an image file as shown in the documentation, but like everyone else I am unable to locate the files created (as the code shows no error, i assume the works)

**Comment by bastifix** [comment] 2020-08-24 23:33
@Zi1989 did you find anything? Just installing the permissions plugin changed nothing for me

**Comment by fragatak** [comment] 2020-08-26 20:00
This is the code that is used with the app first starts up to check permission.

function androidPermissions()
{
    let permissions = cordova.plugins.permissions;
    let list = [
        permissions.WRITE_EXTERNAL_STORAGE,
        permissions.READ_EXTERNAL_STORAGE
    ];

    function error() {
        console.warn('External Read or Write permission is not turned on');
    }

    permissions.checkPermission(list, function (status) {
        if (!status.hasPermission) {
            permissions.requestPermissions(
            list,
            function(status) {
                if (!status.hasPermission) error();
            },
            error
            );
        }
    }, null);
}

document.addEventListener("deviceready", androidPermissions, null);

**Comment by bastifix** [comment] 2020-08-28 04:33
@fragatak thanks! I've the permissions for the storage, but the file content is just "null". Do you have any idea?

**Comment by breautek** [comment] 2022-12-19 03:49
With Android's Scoped Storage model (enforced in API 30 and later), the external storage is no longer discoverable. Some directories are simply not readable (they will give a File not Found error, even if they do exists, such as the `externalRootDirectory`), and other directories will only list files that have been created by your app, but not files created by other apps.

Closing as not a bug.

**Closed by breautek** 2022-12-19 03:49 UTC
Labels: platform: android, support
