### ISSUE TITLE
File path returned undefined.

### ISSUE THREAD

**Issue by mashrurbd** [apache/cordova-plugin-file#435] opened 2020-11-14 07:23 UTC
# Bug Report
The file path is returning undefined.
## Problem
I am checking for images in externalRootDirectory. But the problem is the returned JSON gets undefined. Please help me resolving this issue.
### What is expected to happen?
A json is expected to return like: 
`{'found':true, 'ib_img_url':'/path/to/file'}'`

### What does actually happen?

The json object returning undefined.

### Command or Code

```
function ibx_check_image(path,device_folder)
{
    
    window.resolveLocalFileSystemURL(cordova.file.externalRootDirectory,function (rootDirEntry) {
        rootDirEntry.getDirectory('SnapTook', { create: true }, function (dirEntry) {
            dirEntry.getDirectory(''+device_folder+'', { create: true }, function (subDirEntry) {
                subDirEntry.getFile(''+path+'', { create: false, exclusive: true }, function (fileEntry) {
                    var found = true;
                    var ib_img_url = fileEntry.fullPath;
                    // This returns undefined 
                    return {found, ib_img_url}


                    
                }, function(err)
                {
                    // alert('File not found babe!');
                     var found = false;
                    var ib_img_url = 'none';
                    // This returns undefined 
                    return {found, ib_img_url}                
                });
            }, onErrorGetDir);
        }, onErrorGetDir);
        

    }, getFSFail);


    

}
```

When I call the function like this, the function returns the JSON as undefined.

```
var opfile = ibx_check_image('my_image.jpg','Images');

console.log(opfile) // undefined
```

### Environment, Platform, Device

Android, JavaScript

### Version information

Cordova CLI

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2021-05-02 17:36
Duplicate of https://github.com/apache/cordova-plugin-file/issues/426

**Closed by breautek** 2021-05-02 17:36 UTC
