### ISSUE TITLE
cordova-plugin-file 8.0.0 doesn'work with android 11.0.0

### ISSUE THREAD

**Issue by FranGhe** [apache/cordova-plugin-file#584] opened 2023-07-19 22:18 UTC
First of all, sorry if my english it's not so good...

I developed my app with:
 - cordova-plugin-file 7.0.0 
 - android 11.0.0 
 - and on config.xml <preference name="AndroidPersistentFileLocation" value="Internal" />
and everything was working fine.

At the end of my development I decided to update the plugins and platform... and surprise... cordova-plugin-file 8.0.0 doesn'work with android 11.0.0

To update them I deleted the platform and then the plugin ... I first inserted the plugin and then the platform and during the installation of the plugin for the platform this message appears:
_"Plugin doesn't support this project's cordova-android version. cordova-android 11.0.0. failed version requirement: Skipping 'cordova-plugin-file' for android."_

If I start with cordova run my app crash with message :"Cannot read properties of undefined (reading 'dataDirectory')"

Following some suggestions I changed
`<preference name="AndroidPersistentFileLocation" value="Internal" />`
with
`<preference name="AndroidPersistentFileLocation" value="Compatibility" />`
but nothing changes.

I reinstalled cordova-plugin-file 7.0.0 and I have a waning message like this:
_The android persistent storage location now defaults to "Internal.
Please check this plugin's README to see if your application needs any changes in the config.xml
If this is a new application no changes are required. If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add <preference name="AndroidPersistentFileLocation" value="Compatibility" /> to file config.xml in order for application to find previousely stored files._ 
... but everything works.

Do you have any suggestions?

**Comment by EYALIN** [comment] 2023-07-20 05:43
@FranGhe why you are not upgrading to cordova 12? in 31.8 you will need to upgrade your project to SDK 33, which i don't think will be supported in cordova 11

**Comment by breautek** [comment] 2023-07-20 10:02
> "Plugin doesn't support this project's cordova-android version. cordova-android 11.0.0. failed version requirement: Skipping 'cordova-plugin-file' for android."

v8 requires cordova-android@12 because cordova-android 12 builds with API 33 which this plugin uses.

> The android persistent storage location now defaults to "Internal.
Please check this plugin's README to see if your application needs any changes in the config.xml
If this is a new application no changes are required. If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add to file config.xml in order for application to find previousely stored files.

This is a warning message is more of a notice and only really applies if you have an app that nearly 10 years old. If you had an app that **used** v2 of this plugin, v3+ required `<preference name="AndroidPersistentFileLocation" value="Compatibility" />` to maintain access to stored files. However if you never used `<preference name="AndroidPersistentFileLocation" value="Compatibility" />` or you're building a new app, then you should just use the default and it's safe to ignore the message.

If you need to stay on on cordova-android@11, the you'll need to continue using file plugin 7.

Closing as not a bug.

**Closed by breautek** 2023-07-20 10:02 UTC

**Comment by ganesh-sa** [comment] 2023-08-02 11:09
The same error comes when installing plugin 7 also. Cordova skips installing the plugin.

**Comment by alitalaee** [comment] 2024-05-26 11:58
> AndroidPersistentFileLocation

I had the same issue also when try to install it... 

`
ionic cordova plugin add cordova-plugin-file@7.0.0 --force   

Installing "cordova-plugin-file" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 11.0.0, failed version requirement: >=12.0.0
Skipping 'cordova-plugin-file' for android
Adding cordova-plugin-file to package.json
`

**Comment by breautek** [comment] 2024-05-26 12:41
If you have attempted to install v8, make sure you use `cordova plugin remove cordova-plugin-file` to uninstall the plugin (or whatever the ionic equivalent command is that triggers the cordova command). 

Cordova plugin has a downloaded and installed (for each platform) state. This part I don't really like about Cordova but if you're attempting to install a different version of a plugin that is already downloaded (e.g. it exists inside `/plugins/`) then it will ignore the download, even if it's not the same version and will install the version that is already stored in `/plugins/`, even if it's not the same version being requested.

I feel like this might be what you're experiencing, it's definitely not intuitive behaviour.
