### ISSUE TITLE
Cordova Plugin File doesn't work on Android 13

### ISSUE THREAD

**Issue by JMrJImmy** [apache/cordova-plugin-file#610] opened 2023-10-21 03:36 UTC
### Discussed in https://github.com/apache/cordova/discussions/424

<div type='discussions-op-text'>

<sup>Originally posted by **leonelgregioauler** July 10, 2023</sup>
Good morning! 

What permission should I add to be able to write a .CSV file in the "Documents" folder ? 

I've tried all the permissions below. 

![image](https://github.com/apache/cordova/assets/12154804/e51043b9-e57d-4353-a53d-8320115d9a31)

I got this error: "**onErrorGetDir**". The folder is: **file:///storage/emulated/0/**

![image](https://github.com/apache/cordova/assets/12154804/96fb28cc-aa88-436e-8124-c8de11edffb6)

Remember, this works fine on others versions, like Android 11 or below. Android 12 I haven't tested yet, but it seems to work !

Thank you for now !

</div>

**Comment by JMrJImmy** [comment] 2023-10-25 13:22
I am using the internal storage. The photo is in the applications cache. so the above is irrelevant. Just want to know what to do to a fileURI that is returned from your photo plugin, in order to get a file entry object getfile(fileURI... no longer excepts it ... it is FILE NOT FOUND . How do I format the returned fileURI to get it in the appropriate format for getfile() operation??

**Comment by breautek** [comment] 2023-10-25 14:16
> I am using the internal storage. The photo is in the applications cache

In the details provided in your original post, it shows you were using `cordova.file.externalRootDirectory` which isn't internal storage.

If you're using internal storage then please share the relevant code, or share a [sample reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) that reproduces your issue.

**Comment by JMrJImmy** [comment] 2023-10-26 17:44
Function Mimage_onclick()
  options={quality : 75, correctOrientation: True, _
  allowEdit : False, _
  destinationType : 1}  
  navigator.camera.getPicture(onPictureReturned, onPictureError, options)
End Function
Function onPictureReturned(fileURI)
  varLastSlash = InStrR(fileURI, "/", 0)
  varfileURI = fileURI
  varCacheSubfolder = InStr(1, fileURI, "cache", 0)
  'NewDirectory = Left(varfileURI, varCacheSubfolder - 1) & "/data/data/com.nsbasic.Vantastic/files/"
  varROOT = InStr(1,fileURI, "Android",0)
  PhotoName = Mid(fileURI, varROOT)  'The PhoneGap root file name
  varDate = FormatDateTime(Now, vbYYYYhyphenMMhyphenDD)
  rowindex = $("#GridQuest").jqxGrid("getselectedrowindex")
  'gSelectedCategoryNumber = $("#GridQuest").jqxGrid("getcellvalue", rowindex, "SURVEY_NO")
  varQuestionNO = $("#GridQuest").jqxGrid("getcellvalue", rowindex, "QUESTION_NO")
               If Day(varDate) < 10 Then 
               PhotoDay = "0" & CStr(Day(varDate))
               Else 
               PhotoDay = CStr(Day(varDate))
               End If
               If Month(varDate) <10 Then 
               PhotoMonth = "0" & CStr(Month(varDate))
               Else 
               PhotoMonth = CStr(Month(varDate))
      End If
varPicture = Trim(gSelectedBroker) & "-" & Trim(gSelectedCategoryNumber) & "-" & Trim(gSelectedChainNumber) & "-" & Trim(gSelectedStoreNumber) & "-" & CStr(Year(varDate)) & PhotoMonth & PhotoDay & "-" & Trim(varQuestionNO)
varPicture = varPicture & ".jpg"
Call MovePicS()
End Function
Function onPictureError(message)
  MsgBox "Failed because " & message
End Function
Function MovePicS()
 gfileSystem.root.getFile(PhotoName, {create: False}, gotFileEntryS, fail2)
End Function
Function gotFileEntryS(fe)
  FileEntry = fe
  FileEntry.moveTo(gdataDir, varPicture, SubSuccess2, fail3)
End Function
Function SubSuccess2(entry)
  'MsgBox "Successfully Moved file from Cache:" & vbCRLF & PhotoName & vbCRLF & "To Photos: " & varPicture
   NSB.MsgBox("Press [SAVE ANSWER] to Complete Process...",0,"Photo Successfull") 
End Function
Function fail(error)
  MsgBox "Error Getting File System: " + error.code 
End Function
Function fail2(error)
  MsgBox "Error getting: " + error.code + " --" + PhotoName
End Function
Function fail3(error)
 MsgBox "Error writing: " + error.code + " -- " + varPicture 
End Function

**Comment by breautek** [comment] 2023-11-09 16:01
I don't know if there is a language barrier but the code doesn't appear to be at all related to the original issue.

First you were asking

> What permission should I add to be able to write a .CSV file in the "Documents" folder ?

Then you're showing camera usage, I don't understand how this relates to the CSV file. This thread has kind of gone off the rails so I'm closing it.

I'll say that writing documents to the Documents folder is not possible under android scoped storage system because it forbids write access to file APIs. To do this action, it needs to go through the media store. There are third-party plugins that interfaces with the media store to do this. More info can be found [here](https://github.com/apache/cordova-plugin-file#androids-external-storage-quirks)

**Closed by breautek** 2023-11-09 16:01 UTC
Labels: info-needed
