### ISSUE TITLE
cordova-plugin file works on simulator but not real device?

### ISSUE THREAD

**Issue by crapthings** [apache/cordova-plugin-file#377] opened 2020-02-14 03:49 UTC
i have write an ios share extension, it only works on simulator but not real device.

the framework that i use is meteor 1.9
cordova-ios version 

{
  "ios": "4.5.5"
}

cordova-plugin-file is 6.0.2

this is a working demo on simulator

https://streamable.com/u784i

but on real device, it tells me NOT_FOUND_ERR

![image](https://user-images.githubusercontent.com/1147704/74499836-f28b0900-4f1f-11ea-9d44-a95fa9d1343c.png)

```js
import axios from 'axios'

const fileReaderSync = file => new Promise(resolve => {
  console.log('fileReaderSync', file)
  const reader = new FileReader()
  reader.onloadend = function () {
    console.log(this.result)
    var blob = new Blob([new Uint8Array(this.result)], { type: file.type })
    resolve(blob)
  }
  reader.readAsArrayBuffer(file)
})

const resolveLocalFileSystemURLSync = uri => new Promise(resolve => {
  console.dir(uri)
  console.log(uri)
  window.resolveLocalFileSystemURL(uri, function (fileEntry) {
    console.log('resolveLocalFileSystemURL', fileEntry)
    fileEntry.file(resolve)
  }, function (...args) {
    console.log(args, uri)
  })
})

const uploadFiles = async function (urls) {
  const data = new FormData()

  if (urls.length > 0) {
    for (const item of urls) {
      const file = await resolveLocalFileSystemURLSync(item)
      const blob = await fileReaderSync(file)
      data.append('files', blob)
    }

    axios({
      method: 'post',
      url: 'http://192.168.50.76:3000/api/upload',
      data,
      headers: {'Content-Type': 'multipart/form-data' }
    })
    .then(function (response) {
      alert(JSON.stringify(response, null, 2));
    })
    .catch(function (response) {
      alert(response);
    })
  }
}


Meteor.isCordova && Meteor.startup(function () {
  cordova.shareextension && cordova.shareextension.onFiles(async function (urls) {
    uploadFiles(urls)
  }, console.log)

  cordova.openwith && cordova.openwith.init && cordova.openwith.init(function () {
    cordova.openwith.addHandler(async function (intent) {
      const urls = _.map(intent.items, 'uri')
      uploadFiles(urls)
    })
  }, console.log)
})

```

```
sim

file:///Users/monsterstep/Library/Developer/CoreSimulator/Devices/9823ED69-F740-44E4-A368-4A2C88DC8660/data/Media/PhotoData/OutgoingTemp/D581A7CA-5439-4251-B3FD-18081129D6B2/IMG_0004.JPG

real device

file:///var/mobile/Media/PhotoData/OutgoingTemp/20E08AC5-B9CD-460E-8163-15B1B5ADF1F3/sd1543723877_2.MP4
```

**Comment by breautek** [comment] 2020-02-14 05:18
Can you confirm if this is a duplicate of https://github.com/apache/cordova-plugin-file/issues/346?

**Comment by crapthings** [comment] 2020-02-14 05:50
this is part of swift code

```swift
@objc(ShareExtension) class ShareExtension: CDVPlugin {
    var _command: CDVInvokedUrlCommand?

    override func pluginInitialize() {
        super.pluginInitialize()
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(sendUrls),
            name: NSNotification.Name("CDVPluginHandleOpenURLNotification"),
            object: nil
        )
    }

    @objc func sendUrls() {
        let userDefaults = UserDefaults(suiteName: "group.com.idibwofa6eg9w4.bk46f44qira.shareextension")!
        let urls = userDefaults.array(forKey: "urls")
        let result = CDVPluginResult(status: CDVCommandStatus_OK, messageAs: urls)
        result!.keepCallback = true
        self.commandDelegate.send(result, callbackId: _command!.callbackId!)
    }

    @objc(onFiles:) func onFiles(command: CDVInvokedUrlCommand) {
        self._command = command
    }
}
```

```swift
import MobileCoreServices
import UIKit

class ShareViewController: UIViewController {
    @IBOutlet weak var textarea: UITextView!
    @IBOutlet weak var done: UIButton!

    var userDefaults = UserDefaults(suiteName: "group.com.idibwofa6eg9w4.bk46f44qira.shareextension")!

    override func viewDidLoad() {
        super.viewDidLoad()

        var urls: [String] = []

        guard let extensionItems = extensionContext?.inputItems as? [NSExtensionItem] else {
            return
        }

        let group = DispatchGroup()

        for extensionItem in extensionItems {
            if let itemProviders = extensionItem.attachments {
                for itemProvider in itemProviders {
                    group.enter()
                    itemProvider.loadItem(forTypeIdentifier: kUTTypeItem as String, options: nil, completionHandler: { text, error in
                        urls.append("\(text!)")
                        group.leave()
                    })
                }
            }
        }

        group.notify(queue: .main) {
            self.userDefaults.set(urls, forKey: "urls")
            self.userDefaults.synchronize()
            self.textarea.insertText("done \(urls) \n\n")
            self.openURL(URL(string:"openwith://test")!)
            self.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
        }
    }

    @IBAction func btn(_ sender: UIButton) {
        self.openURL(URL(string:"openwith://test")!)
        self.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
    }

    @objc func openURL(_ url: URL) -> Bool {
        var responder: UIResponder? = self
        while responder != nil {
            if let application = responder as? UIApplication {
                return application.perform(#selector(openURL(_:)), with: url) != nil
            }
            responder = responder?.next
        }
        return false
    }
}
```

**Comment by crapthings** [comment] 2020-02-14 08:31
trying to upgrade cordova-ios to 5.1.1, still same issue

**Comment by crapthings** [comment] 2020-02-15 14:55
hi, i've got problem solved by copy file to  app group container

**Closed** 2020-02-15 15:02 UTC
