### ISSUE TITLE
removeRecursively fails to remove directory and containing files under Android 7.x

### ISSUE THREAD

**Issue by ryaa** [apache/cordova-plugin-file#241] opened 2018-08-17 11:00 UTC
The app creates a temp subdirectory in Download directory and saves several files there. After that 
removeRecursively is invoked to remove this temp directory with the files created. The function returns success however the directory and files are not removed. The file size is 0.

**Comment by janpio** [comment] 2018-08-17 11:07
Do you have some code or even a Github project that can reproduce this problem?
Does it only happen with Android 7.x, not with <7 or newer?

**Comment by ryaa** [comment] 2018-08-17 13:08
> Do you have some code or even a Github project that can reproduce this problem?

This is a private ionic cordova mobile application and unfortunately I can't grant access to the repository. I can build apk file in debug mode and share this if you are ready to debug it (I usually connect the smartphone with the app running to my laptop and use chrome to debug the source code). I will provide all the details about the appropriate code which makes removeRecursively call.

Please note that i also tried to remove individual files in the temp dir and then remove the dir itself and the result is the same. The directory is not removed and all the files have 0 size.

**Comment by ryaa** [comment] 2018-08-17 13:09
One more thing - the temp directory is created in the standard Android Download directory. Could it be causing the problem?

**Comment by janpio** [comment] 2018-08-17 13:36
I am not going to debug or try to reproduce this - I just try to collect all necessary information for an Android developer to do so. A code sample or better even working project would help a lot (Best is a new Cordova project created with `cordova start` and just the absolute necessary minimum implemented to reproduce the bug, then put on Github on a public repository).

**Comment by ryaa** [comment] 2018-08-17 15:06
I think that problem might be related to the permission.
The path for temp directory created is cordova.file.externalRootDirectory + 'Download/<APP_NAME>/temp/<GUID>' (I store some files there) and then use removeRecursively to remove the entire directory with all the files there.

When I changed to use another path cordova.file.dataDirectory + 'Download/<APP_NAME>/temp/<GUID>' everything seems to be working fine. I will be testing more and share if I find anything else.

**Comment by breautek** [comment] 2020-08-06 08:19
Closing due to staleness.

**Closed by breautek** 2020-08-06 08:19 UTC
Labels: bug, platform: android
