### ISSUE TITLE
cordova-plugin-file overwrites the global File variable

### ISSUE THREAD

**Issue by JoCa96** [apache/cordova-plugin-file#453] opened 2021-01-28 14:53 UTC
# Bug Report
Hi, we had this plugin in our Capacitor project as a dependency of `cordova-plugin-advanced-http`.

It is not possible to use the [Browsers File API](https://developer.mozilla.org/en-US/docs/Web/API/File/File) with this plugin in Capacitor on iOS.

The following snippet will not work correctly:
```javascript
var file = new File(["foo"], "foo.txt", {
  type: "text/plain",
});
```

## Problem
The `cordova-plugin-file` is overwriting the global/globalThis/window File variable.

I never actively used this Plugin, but skimmed through the docs and it doesn't seem like this behaviour is intended.

### What is expected to happen?
I expect to be able to use the Browsers `File` API as described by [MDN](https://developer.mozilla.org/en-US/docs/Web/API/File/File) to create a File instance.

### What does actually happen?
An incorrect File instance is created, which can not be used as describe by [MDN](https://developer.mozilla.org/en-US/docs/Web/API/File/File) to create a File instance.

## Information

We are only building an iOS App, so I can only confirm this bug for iOS.

### Command or Code
Create an Capacitor iOS project and install the `cordova-plugin-file` package.

Build the iOS app and use XCode to build and run the App on an iPhone/iPad connected via USB.
Use Safari DevTools to debug the Capacitor App and run the following snippet.
Inspect the `file` variable or inspect the `File` protoype's constructor and you will notice that it is not the Browsers native `File` API.

```javascript
var file = new File(["foo"], "foo.txt", {
  type: "text/plain",
});
```

### Environment, Platform, Device
* Capacitor 2.4.6
* iOS 14.3
* iPhone 8

### Version information
```json
    "@capacitor/cli": "2.4.6",
    "@capacitor/core": "2.4.6",
    "@capacitor/ios": "^2.4.6",
    "ionic": "^5.4.14",
    "@ionic/angular": "^5.4.1",
    "@ionic/angular-toolkit": "~2.0.0",
    "ionic-native": "^2.9.0",
    "@ionic-native/file-transfer": "^5.29.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-advanced-http": "^2.2.0",
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2021-01-28 15:11
> I never actively used this Plugin, but skimmed through the docs and it doesn't seem like this behaviour is intended.

This plugin has its own `File` class, which is in no way related to the browser's native `File` class. This is intentional... but it was decision from way back in the day when browsers didn't really had a usable `File` class (outside of the readonly `File` instance obtained when using the `<input type="file">` field)

Personally, I do agree, the plugin should avoid clobbering features provided by the browser. But changing this would probably require a discussion on the [mailing list](https://cordova.apache.org/contact/) as this plugin is a dependency of several other plugins. I suppose the simplest change (and simplest migration) would just change the clobber space to `cordova.file` or something.

**Comment by Go4th** [comment] 2021-02-02 14:46
@breautek  how do I update the clobber space to using the explicit namespace cordova.file as I'm having this same problem. That, or is it possible to create a File Reference using the cordova plugin that will be able to be Read in my API?

**Comment by Go4th** [comment] 2021-02-02 14:48
@JoCa96 where you able to resolve this issue? How?

**Comment by breautek** [comment] 2021-02-02 14:51
> @breautek how do I update the clobber space to using the explicit namespace cordova.file as I'm having this same problem. That, or is it possible to create a File Reference using the cordova plugin that will be able to be Read in my API?

The only way to do this is to fork the plugin and change the `plugin.xml`:

https://github.com/apache/cordova-plugin-file/blob/a4a7bfe2aa48f5c44eb8af264c1c6540ea4dd072/plugin.xml#L48-L50

Doing so may break things that depend on this plugin however, and may require other changes within the plugin's JS sources itself.

A safer workaround might be to capture a reference to the original `File` object. Do this before you load the `cordova.js` file.

**Comment by Go4th** [comment] 2021-02-02 15:32
@breautek Thanks man. 
Appears that the File Plugin reference is global beyond the component/utility in which it's used due to being imported into the AppModule, but updating the clobber did work. Thanks for the tip. Hopefully cordova will update this namespace collision in a later version as using the browser's File() method is very useful in modern development.

**Comment by JoCa96** [comment] 2021-04-27 06:39
@Go4th Sorry, I missed the notification for your comment. We were just able to remove the `cordova-plugin-advanced-http` plugin, because we didn't actively use it. Not really a fix, sorry.

**Comment by Tukkan** [comment] 2021-06-17 20:31
Hehe, I spent like 4 hours figuring out why my Files are wrongly loaded until I found out that the API has been replaced.

The dirty hack would be to put 

```
  <script>
    window.NativeFile = File;
  </script>
```
  
  in index.html header so that we could still have the reference to old File API.

**Comment by dominic-simplan** [comment] 2021-07-13 15:44
Probably duplicate of #316.

**Comment by breautek** [comment] 2023-01-25 00:45
I removed iOS from the title since this isn't actually iOS specific, it's part of the plugin for all platforms.

**Comment by breautek** [comment] 2023-01-25 00:45
duplicate https://github.com/apache/cordova-plugin-file/issues/453

**Closed by breautek** 2023-01-25 00:45 UTC
