### ISSUE TITLE
Not Allowed to load local resource

### ISSUE THREAD

**Issue by fahad-larasoft** [apache/cordova-plugin-file#444] opened 2020-12-10 07:37 UTC
I am getting an error while recording a video/audio and playing it through Quasar Vue.js App using Cordova Plugins i.e. to resolve file system we are using: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html and to record audio/video we're using: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-media-capture/index.html.

Here are some screenshots of error and relevant codebase:

<img width="815" alt="Screenshot 2020-12-09 at 2 37 38 PM" src="https://user-images.githubusercontent.com/7126820/101735475-c7435d00-3ae3-11eb-85fe-4f0d4ce3181d.png">
<img width="907" alt="Screenshot 2020-12-09 at 2 46 41 PM" src="https://user-images.githubusercontent.com/7126820/101735483-cad6e400-3ae3-11eb-9ba3-fb884ff6da1e.png">

- Can anyone help how to get rid from this **Not Allowed .,..** error and play audio/video in the quasar vuejs app?
- Also how should we send the recorded audio/video file to backend Server? Do we need to convert **MediaFile** or **FileEntry** Object to **Base64** string and send it to server?

Thanks

**Comment by breautek** [comment] 2020-12-18 00:15
> Also how should we send the recorded audio/video file to backend Server? Do we need to convert MediaFile or FileEntry Object to Base64 string and send it to server?

I would strongly advise use base64 encoded strings. They explode the memory representation of your binary files by 35-40%. You can read these files as `Blob` instead and send them to your backend via `XMLHttpRequest`.

> Can anyone help how to get rid from this Not Allowed 

I have a feeling this is due to a change in API 29. There is already an API 29 fixed merged in master, but this hasn't been released. Can you try to see if this issue reproduces when using the development version of this plugin? You can install it using the following command:

`cordova plugin add https://github.com/apache/cordova-plugin-file.git`

Don't forgot to uninstall the plugin first before replacing it.

**Comment by fahad-larasoft** [comment] 2020-12-23 11:57
@breautek I tried using: `cordova plugin add https://github.com/apache/cordova-plugin-file.git` and it added following entry in `package.json`

<img width="795" alt="Screenshot 2020-12-23 at 4 26 51 PM" src="https://user-images.githubusercontent.com/7126820/102993800-a812e980-453f-11eb-84d9-e5972ad90b00.png">


Afterwards when I try to run: `quasar dev -m cordova -T android` it throws following errors on terminal

<img width="1072" alt="Screenshot 2020-12-23 at 4 52 12 PM" src="https://user-images.githubusercontent.com/7126820/102993803-aa754380-453f-11eb-849c-514ac2dcccf1.png">

**Comment by breautek** [comment] 2021-02-14 02:33
Sorry for the lack of response...

That's strange, cause none of those classes have went away.

I'd try...:

1. removing all the dependants of the file plugin, which looks like the `filetransfer` plugin and the `mediacapture` plugin,
2. remove the `file` plugin.
3. reinstall the `file` plugin via git
4. install the file transfer and media capture plugin again

**Comment by anandtripathi5** [comment] 2021-02-21 11:08
@fahad-larasoft Any luck on this

**Comment by fahad-larasoft** [comment] 2021-02-25 08:57
@breautek the weird thing is we're getting same errors even in new fresh projects. So the problem seems to be with the plugin.

**Comment by fahad-larasoft** [comment] 2021-02-25 08:57
@anandtripathi5  no luck

**Comment by breautek** [comment] 2021-05-02 17:38
Duplicate of https://github.com/apache/cordova-plugin-file/issues/426

**Closed by breautek** 2021-05-02 17:38 UTC

**Comment by bruno-machado** [comment] 2022-09-06 10:31
ionic cordova plugins rm cordova-plugin-ionic-webview
ionic cordova plugins add cordova-plugin-ionic-webview@1.2.1
cordova clean android

it worked for me
