### ISSUE TITLE
Error 9 when trying to save a file on android 10 folder Download

### ISSUE THREAD

**Issue by gmoraiz** [apache/cordova-plugin-file#527] opened 2022-06-25 02:46 UTC
# Bug Report
When I try to save a file in the download/documents folder (on a mobile with android 10), the following error occurs: 
`FileError {code: 9}`
The strange thing is that on android 11 and 12 it works, on 9, 8 and 7 too...

### Version information
android-targetSdkVersion: 30
android-minSdkVersion: 19
cordova-plugin-file: 7.0.0
cordova: 10
device: Galaxy Nexus API 29 Android

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment] 2022-12-19 03:24
The following code works for me assuming that my app has ownership of the file (e.g. the file wasn't written by another app)

```javascript
document.addEventListener('deviceready', onDeviceReady, false);

var testFiles = async function() {
    window.resolveLocalFileSystemURL(cordova.file.externalRootDirectory + 'Download', (downloadsDirEntry) => {
        console.log('DOWNLOADS', downloadsDirEntry);
        downloadsDirEntry.getFile('test1.txt', { create: true }, (fileEntry) => {
            fileEntry.createWriter((writer) => {
                writer.onwriteend = () => {
                    console.log('file written');
                };

                writer.onerror = (error) => {
                    console.error('WRITE ERROR', error);
                };

                writer.write(new Blob(['Hello!'], { type: 'text/plain'}));
            });
        }, (error) => {
            console.error('FILE OPEN', error);
        })
    }, (error) => {
        console.error('DIR READ', error);
    });
};

function onDeviceReady() {
    // Cordova is now initialized. Have fun!

    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
    document.getElementById('deviceready').classList.add('ready');

    testFiles();
}
```

The above code writes the file and can be observed by using `adb pull /storage/emulated/0/Download/test1.txt ./` that both the file exists and contains the contents written.

Tested against target API 32 / API 32 emulator. Can you please compare, or share some code that reproduces the issue?

**Comment by breautek** [comment] 2023-01-25 00:24
The bug is with API 29 not supporting filesystem access via Filesystem APIs. This was fixed in API 30.

> To help your app work more smoothly with third-party media libraries, Android 11 allows you to use APIs other than the [MediaStore](https://developer.android.com/reference/android/provider/MediaStore) API to access media files from shared storage using [direct file paths](https://developer.android.com/training/data-storage/shared/media#direct-file-paths).

https://developer.android.com/about/versions/11/privacy/storage

Unfortunately from a filesystem plugin standpoint, there is nothing we can do to work around this bug.

From an application standpoint, using a [MediaStore](https://www.npmjs.com/search?q=ecosystem%3Acordova%20mediastore) plugin may be a workaround.

**Closed by breautek** 2023-01-25 00:24 UTC
Labels: platform: android, info-needed, android-scoped-storage
